spring.application.name=capstone

//dev
spring.datasource.url=jdbc:postgresql://10.4.88.37:5432/financeCare_test
spring.datasource.username=root
spring.datasource.password=password123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

