spring.application.name=poc

spring.datasource.url=jdbc:postgresql://10.4.88.37:5432/financeCare_DB
spring.datasource.username=root
spring.datasource.password=password123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.url=http://10.4.88.37:9000
minio.access-key=admin
minio.secret-key=password123
minio.bucket-name=poc

