spring.application.name=capstone
server.port=8080
server.servlet.context-path=/api

#dev
spring.datasource.url=jdbc:postgresql://10.4.88.37:5432/financeCare_DB
spring.datasource.username=root
spring.datasource.password=password123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.redis.host=10.4.88.37
spring.redis.port=6379
spring.redis.timeout=60000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cp25ms2.financecare@gmail.com
spring.mail.password=srbpwovznhlktcqt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp

line.channel-id=2008279064

app.mail.enabled=true
